name: Checkout

on:
  workflow_dispatch:
  schedule:
    # Randomize the cron schedule if needed, but currently fixed as per your setup
    - cron: '15 13 * * 1-5' # 6:45 PM UTC on Monday to Friday (12:15 AM IST next day)

jobs:
  random-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Random Delay
        id: random-delay
        run: |
          # Generate a random number between 60 and 300 (1 to 5 minutes in seconds)
          delay=$((RANDOM % 241 + 60))
          echo "Sleeping for $delay seconds"
          sleep $delay
          echo "::set-output name=delay::$delay"

      - name: Make Login Request
        id: login
        run: |
          response=$(curl -s -X POST https://mybuddy.botmantra.ai/backend/backend/login -H "Content-Type: application/json" -d '{"email": "utkarsh.sao@botmantra.com","password": "password"}')
          echo "Response: $response"
          token=$(echo $response | jq -r '.access_token')
          echo "Access Token: $token"
          echo "::set-output name=access_token::$token"

      - name: Post Attendance
        run: |
          curl -s -X POST https://mybuddy.botmantra.ai/backend/backend/postAttendance \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ steps.login.outputs.access_token }}" \
          -d '{"emp_id": "0100","status": "check_out","work_type": "Work From Office","ip_address": "106.51.85.101"}'
