name: Randomized Weekday API Requests

on:
  workflow_dispatch:
  schedule:
    # - cron: '45 4 * * 1-5' # 10:00-10:30 IST on Monday to Friday
    # - cron: '15 13 * * 1-5' # 10:00-10:30 IST on Monday to Friday
jobs:
  random-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Set Check Type
        id: type-check
        run: |
          if [[ "${GITHUB_EVENT_SCHEDULE}" == "15 13 * * 1-5" ]]; then
            echo "Triggered by second schedule"
            echo "::set-output name=type::check_out"
          else
            echo "Triggered by first schedule"
            echo "::set-output name=type::check_in"
          fi
          
      # - name: Introduce Random Delay
      #   id: random-delay
      #   run: |
      #     # Generate a random number between 0 and 300 seconds (0 to 5 minutes)
      #     DELAY=$((RANDOM % 301))
      #     echo "Sleeping for $DELAY seconds..."
      #     sleep $DELAY

      - name: Make Login Request
        id: login
        run: |
          response=$(curl -s -X POST https://mybuddy.botmantra.ai/backend/backend/login -H "Content-Type: application/json" -d '{"email": "utkarsh.sao@botmantra.com","password": "password"}')
          echo "Response: $response"
          token=$(echo $response | jq -r '.access_token')
          echo "Access Token: $token"
          echo "::set-output name=access_token::$token"

      - name: Post Attendance
        run: |
          curl -s -X POST https://mybuddy.botmantra.ai/backend/backend/postAttendance \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ steps.login.outputs.access_token }}" \
          -d '{"emp_id": "0100","status": "${{ steps.type-check.outputs.type }}","work_type": "Work From Office","ip_address": "106.51.85.101"}'
          
          # echo "current_date=$(date -u +"%d-%m-%Y")" >> $GITHUB_ENV
          
          # curl -s -X POST https://mybuddy.botmantra.ai/backend/backend/createTimesheet \
          # -H "Content-Type: application/json" \
          # -H "Authorization: Bearer ${{ steps.login.outputs.access_token }}" \
          # -d '{"emp_id":"0101","timesheet_date":"${{ env.current_date }}","details":[{"wbs_id":"WsBO5Ge2Ztclf776Qvrw7","wbs_code":"P23-PEAKALPHA","wbs_description":"Peak Alpha","wbs_percentage":100}]}'
          
